# 도커 컴포즈의 버전
version: "3"

# 이곳에 실행하려는 컨테이너
services:
  # 컨테이너 이름
  redis-server:
    # 컨테이너에서 사용하는 이미지
    image: "redis"
  # 컨테이너 이름
  node-app:
    # 현 디렉토리에 있는 Dockerfile
    build: .
    # 포트 맵핑 => 로컬 포트:컨테이너 포트
    ports:
      - "5000:8080"
